
[package]
name = "BibCiTeX"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
[workspace]
members = [".", "bibcitex-core"]

[workspace.package]
version = "0.1.0"
authors = ["tangxiangong <tangxiangong@gmail.com>"]
edition = "2024"
description = "A BibTeX citation inserter tool"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
arboard = "3.6"
biblatex = "0.10"
dioxus = { version = "0.6", features = ["desktop"] }
dirs = "6.0.0"
enigo = "0.5"
opener = "0.8.2"

[dependencies]
dioxus = { workspace = true }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
