[package]
name = "bibcitex-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
biblatex = { workspace = true }
fs-err = { workspace = true }
thiserror = { workspace = true }
